### ISSUE TITLE
cannot find this plugin in homebridge

### ISSUE THREAD

**Issue by stekki007** [oznu/ffmpeg-for-homebridge#101]
Maybe dumb question, but when searching for plugins in Homebridge, I cannot find this one.  Someone can help me?
I am new to this 

Thanks!

**Comment by hjdhjd** [comment]
This isn't intended for use directly by end users, it's a component used within other camera plugins. You're going to need to go look at plugins like homebridge-camera-ffmpeg or homebridge-camera-ui for generic support, or brand-specific plugins like homebridge-unifi-protect for UniFi cameras.

TL;DR: this package is for developers not end users, but the two plugins above should begin to point you in the right direction!

**Comment by stekki007** [comment]
Hi,Thanks, but is my doorbird plugin that pointed me to this page.  Are there others too that will work?RegardsSent from my iPhoneOn 25 Nov 2024, at 02:52, hjdhjd ***@***.***> wrote:﻿
Closed #101 as completed.
