### ISSUE TITLE
armv6 binaries

### ISSUE THREAD

**Issue by normen** [oznu/ffmpeg-for-homebridge#70]
**Is your feature request related to a problem? Please describe:**
The binaries don't work on RasPi zero W

**Describe the solution you'd like:**
Binaries for armv6 would be nice

**Describe alternatives you've considered:**
Compiling them myself on my Pi Zero W seems unrealistic

**Additional context:**

**Comment by hjdhjd** [comment]
Arm6 is explicitly unsupported moving forward and at the moment, there are no current plans to revisit this. Many Linux distributions have (or are about to) stop supporting arm6 as well. Thanks for the request.

**Comment by normen** [comment]
Given that this whole thing is a "workaround for unsupported" I thought it might fit the frame. Seems not.
