### ISSUE TITLE
Support ALSA capture / playback

### ISSUE THREAD

**Issue by normen** [oznu/ffmpeg-for-homebridge#71]
**Is your feature request related to a problem? Please describe:**
Currently, when using e.g. a Pi Zero 2 W as a camera, one can not use the ALSA audio interface for the audio capture or backchannel.

e.g. `"source": "-f video4linux2 -input_format h264 -video_size 1280x720 -framerate 30 -i /dev/video0 -f alsa -channels 1 -i plughw:1"`
or `"returnAudioTarget": "-f alsa plughw:1"`

fail in that case.

**Describe the solution you'd like:**
On linux systems, `libasound2-dev` should be installed prior to compiling ffmpeg, that should compile the ALSA support automatically.

**Describe alternatives you've considered:**
Compiling ffmpeg myself, which I do but it seems cumbersome.

**Additional context:**

**Comment by normen** [comment]
still valid

**Comment by hjdhjd** [comment]
Unlikely to add this feature in the near term, but willing to review and assess a potential PR that addresses this so long as it creates no regressions and works correctly in a fully static environment across current Raspbian distributions. 

Adding this for emphasis: this package’s primary purpose is to support the needs of Homebridge camera plugin developers, not provide a general solution for all use cases. :smile: Thanks for the request.

**Comment by normen** [comment]
> Adding this for emphasis: this package’s primary purpose is to support the needs of Homebridge camera plugin developers, not provide a general solution for all use cases. 😄 Thanks for the request.

What if not making your own two-way audio camera from a Pi is a better use for homebridge camera capabilities? Anyway, I suppose you're looking at the build script mess in similar horror as me when implying that "adding this feature" might be hard.

**Comment by Vaxter** [comment]
> Adding this for emphasis: this package’s primary purpose is to support the needs of Homebridge camera plugin developers, not provide a general solution for all use cases. 😄 Thanks for the request.

I am developing a kit to connect your analog intercom to Homebridge as a "Video Doorbell" and having a possibility to stream sound from an Alsa device would be much helpful.
Right not, in order to use my plugin, future users would have to compile ffmpeg themselves.

**Comment by hjdhjd** [comment]
As I said previously - unlikely to be a priority but happy to review PRs.
