### ISSUE TITLE
Latest binary segfaults on execute on Raspberry Pi 5

### ISSUE THREAD

**Issue by asavill** [oznu/ffmpeg-for-homebridge#72]
**Describe The Bug:**
When using the latest binary (2.1.1) for ffmpeg it segfaults on a Pi 5 running Raspbian (bookworm), even when running basic -version commands.

**To Reproduce:**
Execute the binary on Raspberry Pi 5

**Expected behavior:**
No segfault.

**ffmpeg output:**
Segmentation fault

**Environment:**

* **Operating System**: 
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

**Comment by hjdhjd** [comment]
Thanks for the report - will look into it. It’s early days for RPi 5…support is tested through RPi 4 at the moment.

**Comment by asavill** [comment]
> Thanks for the report - will look into it. It’s early days for RPi 5…support is tested through RPi 4 at the moment.

No problem. If you're struggling with sourcing hardware, I can try and help out with testing.

FWIW, hardware encoding also appears to be broken but it makes sense to retest that once the latest binary is fixed. I can create a separate issue then (if it's still not working)

**Comment by itomaldonado** [comment]
this is still happening, any workarounds?

**Comment by hjdhjd** [comment]
Raspberry Pi 5 is currently unsupported, as documented in the README. No further updates at this time.
