### ISSUE TITLE
ffmpeg results in segmentation fault

### ISSUE THREAD

**Issue by griff16** [oznu/ffmpeg-for-homebridge#73]
**Describe The Bug:**
I have a raspberry pi zero W with 8GB micro SD card, and I installed it with official home bridge OS image. 
When I type any command related to ffmpeg, it shows segmentation fault. such as ffmpeg -version. 
memory still has about 100MB free space. I have installed the ffmpeg by using sudo apt

**To Reproduce:**
ffmpeg -version

**Expected behavior:**
show version

**ffmpeg output:**
segmentation fault

```
Run `ffmpeg` in a terminal window and post the output below
```

**Screenshots:**

<img width="330" alt="Screenshot 2024-01-21 at 13 35 37" src="https://github.com/homebridge/ffmpeg-for-homebridge/assets/36973750/300b5099-46e8-4287-9ba8-ef1b3d9b74bb">

**Environment:**

* **Operating System**: 
* 
<img width="480" alt="Screenshot 2024-01-21 at 13 37 04" src="https://github.com/homebridge/ffmpeg-for-homebridge/assets/36973750/6aba6b7e-eacc-42b7-8f59-bd9c0d47cf1e">

**Comment by tsightler** [comment]
I'm not 100% sure, but I think this is because Pi Zero uses arm6hf binaries, while binary provided by this project is armv7.  I've seen this reported on various projects that provide armv7 binaries as armv7 architecture has instructions that do not exist on armv6 used by Pi Zero.

**Comment by hjdhjd** [comment]
As noted on the homepage arm6 architectures are not supported. This isn't a bug - we have deprecated all support for arm6.

Thanks for the report.
