### ISSUE TITLE
Update to FFmpeg 6.1.1

### ISSUE THREAD

**Issue by HenryGelderbloem** [oznu/ffmpeg-for-homebridge#76]
**Describe the solution you'd like:**
Can you update ffmpeg-for-homebridge to use FFMpeg 6.1.1? This version has significant number of changes including support for many more video codecs, an apparent reduction in the binary size, and support for multi-threading using the ffmpeg cli. These could have significant benefits for Homebridge users.

**Additional context:**
This is likely the last release before FFmpeg 7.0 is released so could tide this project over for a while until FFmpeg 7.x is stable and tested for Homebridge.

**Comment by hjdhjd** [comment]
In short: no.

Updates will happen to FF4H based on the needs we have within the Homebridge camera developer community, and will tend to be measured and infrequent. We aren't chasing the latest and greatest of everything, and we certainly have no intention of supporting all the codecs out there.

If you're looking for prebuilt binaries chasing the latest versions of FFmpeg and a complete complement of codecs and capabilities...this isn't the project for you. 😄 

We always welcome PRs and contributions where they make sense, and will review PRs when contributed.

**Comment by n0rt0nthec4t** [comment]
Completed under 04cee63338a962723862a83c29d2501a5d5fcccb
