### ISSUE TITLE
Hardware Acceleration support for vaapi

### ISSUE THREAD

**Issue by JustAnotherPU** [oznu/ffmpeg-for-homebridge#79]
Hi there,

I tried to use hardware acceleration with ffmpeg-for-homebridge but it seem to not support amd or nvidia gpu, but ffmpeg does.

Any idea or eta on adding support to those platforms ? 

Thank you

**Comment by hjdhjd** [comment]
No plans to support it. Thanks.

FF4H is not a general purpose solution - FF4H exists for a very specific set of narrow use cases as documented in the README. You’re always welcome (and in fact encouraged) to compile your own FFmpeg or use what comes in your distributions or other options out there.
